### ISSUE TITLE
Support bulk sending SMS

### ISSUE THREAD

**Issue by baoc75** [NdoleStudio/httpsms#104]
Allow users to send multiple messages to multiple phone numbers with a delay between each message.

**Comment by AchoArnold** [comment]
Hello @baoc75 
Could you elaborate more on your use case? Which type of delay should we set should it be configurable? Currently, if you send multiple messages with the API the messages will be spread out based on the configured messages/second throughput.

e.g Currently, If you send 100 messages in parallel and you have the configuration of 2 SMS / minute, the application will actually send 1 SMS every 30 seconds using the phone.

Does this solve the issue for you?

**Comment by baoc75** [comment]
Hi @AchoArnold, as the documentation don't have an endpoint where I can pass multiple phone numbers. So if I want to send to 100 numbers, I would have to initiate 100 requests. Please correct me if I am wrong.
Regarding the rate limit, thanks for your clarification, I can limit the number of messages right now.
By the way, the software is easy to use 😁

**Comment by AchoArnold** [comment]
Yes you'll have to send 100 requests. I think even if we do multiple phone numbers via API, we still need to split the bulk messages to 100 individual messages before it is sent on the phone.

We can create an additional code to do this at the API level but at the mean time you can also do it on your end.

Out of curiosity, is there a specific issue with sending 100 requests instead of 1 request with 100 phone numbers?

**Comment by AchoArnold** [comment]
Hello @baoc75  I implemented a bulk send API, check it out and tell me what you think https://api.httpsms.com/index.html#/Messages/post_messages_bulk_send

**Comment by baoc75** [comment]
Hello, @AchoArnold. I read your documents. It's exactly what I'm looking for.
About your question, my goal is to make as few HTTP requests as possible. Sending more HTTP requests consumes more bandwidth and resources, and increases the chance of failure.
